recipe: default.v1
assistant_id: ai_astro_omkar
language: en

pipeline:
  - name: LLMCommandGenerator
    llm:
      model_group: gemini
    # prompt_template: prompts/command_generator.jinja2
    flow_retrieval:
      embeddings:
        model_group: gemini_embeddings
  - name: "components.gemini_nlu.GeminiNLUComponent"
    gemini_api_key: ${GEMINI_API_KEY}

policies:
  - name: FlowPolicy
  # - name: EnterpriseSearchPolicy
  #   llm:
  #       model_group: gemini
  #   embeddings:
  #     model_group: gemini_embeddings
  - name: RulePolicy
